---
version: '3'
services:
  dbclient:
    build: .
    container_name: mysql-client
    environment:
      - ACTION_DATABASE=create
      - ACTION_DATABASE_NAME=testdb
      - ACTION_USER=create
      - ACTION_USER_NAME=test-user
      - ACTION_USER_PASSWORD=adminadmin123
      - ACTION_USER_ALLOWED_HOSTS=%
    volumes:
      - .mysql-conf:/etc/mysql/my.cnf
    depends_on:
      database:
        condition: service_healthy
    networks:
      - database

  database:
    image: mysql:5.7
    container_name: dummy-mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysql" ,"--password=root", "--user=root", "--execute=SHOW DATABASES;"]
      interval: 15s
      timeout: 20s
      retries: 5
      start_period: 15s
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - database

networks:
  database: